import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    parallel,
}: {
    children: React.ReactNode;
    parallel: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                {children}
                <div>{parallel}</div>
            </body>
        </html>
    );
}
