import {ReactNode} from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
      <section>
        <h1>
          my 페이지
        </h1>
        {children}
      </section>
  )
}
