import { ReactNode } from 'react';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Layout({
    children,
    parallel1,
    parallel2,
}: {
    children: ReactNode;
    parallel1: ReactNode;
    parallel2: ReactNode;
}) {
    return (
        <>
            {children}
            <div>
                <h1>?????????</h1>
                {parallel1}
                {parallel2}
            </div>
        </>
    );
}
